extends: stylelint-config-sass-guidelines
rules:
  selector-class-pattern: "^[a-zA-Z][a-zA-Z0-9_-]+$"
  selector-no-qualifying-type:
  - true
  - ignore:
    - attribute
    - class
    - id
  selector-max-compound-selectors: 9
